CREATE ROLE incident_api LOGIN PASSWORD 'local-api';
CREATE ROLE incident_agent LOGIN PASSWORD 'local-agent';
CREATE ROLE incident_source LOGIN PASSWORD 'local-source';
CREATE SCHEMA business AUTHORIZATION incident_api;
CREATE SCHEMA agent AUTHORIZATION incident_agent;
CREATE SCHEMA sources;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA sources TO incident_source, incident_api;
SET ROLE incident_api;
SET search_path=business;
CREATE TABLE schema_version(version int PRIMARY KEY);
INSERT INTO schema_version VALUES(1);
CREATE TABLE members(subject text, team text, role text NOT NULL CHECK(role IN ('investigator','approver')), PRIMARY KEY(subject,team));
CREATE TABLE admins(subject text PRIMARY KEY);
CREATE TABLE services(id text PRIMARY KEY, team text NOT NULL, name text NOT NULL, repo text NOT NULL, watermark bigint NOT NULL DEFAULT 1, enabled bool NOT NULL DEFAULT true);
CREATE TABLE investigations(id uuid PRIMARY KEY, team text NOT NULL, service text REFERENCES services(id), subject text NOT NULL, symptom text NOT NULL, start_at timestamptz NOT NULL, end_at timestamptz NOT NULL, timezone text NOT NULL, status text NOT NULL, idem text NOT NULL, request_hash text NOT NULL, report jsonb, manifest jsonb, source_version bigint NOT NULL, seq bigint NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(subject,idem));
CREATE INDEX inv_team_list ON investigations(team,created_at DESC,id);
CREATE TABLE jobs(id uuid PRIMARY KEY REFERENCES investigations(id), state text NOT NULL DEFAULT 'queued', owner text, generation int NOT NULL DEFAULT 0, lease_until timestamptz, available_at timestamptz NOT NULL DEFAULT now(), attempts int NOT NULL DEFAULT 0, last_error text, last_callback text, result_hash text);
CREATE INDEX job_claim ON jobs(state,available_at,lease_until);
CREATE TABLE events(investigation uuid REFERENCES investigations(id), seq bigint NOT NULL, kind text NOT NULL, payload jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(investigation,seq));
CREATE TABLE actions(id uuid PRIMARY KEY, investigation uuid NOT NULL REFERENCES investigations(id), version int NOT NULL, state text NOT NULL, target text NOT NULL, title text NOT NULL, body text NOT NULL, digest text NOT NULL, evidence_hash text NOT NULL, source_version bigint NOT NULL, approved_by text, approved_digest text, approved_version int, result jsonb, marker text UNIQUE NOT NULL, updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(investigation));
CREATE INDEX actions_state ON actions(state,updated_at);
CREATE TABLE approvals(id uuid PRIMARY KEY, action uuid REFERENCES actions(id), version int, digest text, evidence_hash text, subject text, decision text, created_at timestamptz DEFAULT now());
CREATE TABLE feedback(id uuid PRIMARY KEY, investigation uuid REFERENCES investigations(id), subject text, helpful bool, confirmed bool, final_cause text, created_at timestamptz DEFAULT now());
CREATE TABLE memories(id uuid PRIMARY KEY, investigation uuid REFERENCES investigations(id), service text REFERENCES services(id), team text, content text, status text DEFAULT 'candidate', reviewer text, source_version bigint, expires_at timestamptz, created_at timestamptz DEFAULT now());
CREATE TABLE badcases(id uuid PRIMARY KEY, investigation uuid REFERENCES investigations(id), category text NOT NULL, label text, reviewer text, status text DEFAULT 'candidate', manifest jsonb, created_at timestamptz DEFAULT now());
INSERT INTO members VALUES ('alice','orders','approver'),('bob','orders','investigator'),('carol','payments','approver');
INSERT INTO admins VALUES('admin');
INSERT INTO services VALUES ('svc-17','orders','订单服务','local/incident-demo',1,true),('svc-23','payments','支付服务','local/incident-demo',1,true);
RESET ROLE;
CREATE TABLE sources.deployments(id text PRIMARY KEY, service text NOT NULL, app_id text NOT NULL, version text NOT NULL, commit_sha text NOT NULL, event_time timestamptz NOT NULL, watermark bigint NOT NULL, deleted bool DEFAULT false);
GRANT SELECT ON ALL TABLES IN SCHEMA sources TO incident_source, incident_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA sources GRANT SELECT ON TABLES TO incident_source, incident_api;
