import React,{useEffect,useRef,useState} from 'react';
import{createRoot}from'react-dom/client';
import './style.css';
import {QueryWorkbench} from './QueryWorkbench';
type Evidence={id:string;source:string;locator:string;event_time:string;collected_at:string;version:string;sha256:string;snippet:unknown};
type Claim={text:string;evidence:string[];label?:string};
type Report={answer?:string;answer_evidence?:string[];answer_validation?:string;retrieval?:{total_in_query?:number;matched?:number;evidence_count?:number;sampled?:boolean;terms?:string[]};impact:string;facts:Claim[];candidates:Claim[];conflicts:Claim[];missing:string[];next_steps:string[];evidence:Evidence[];mode:string};
type Action={version:number;state:string;target:string;title:string;body:string;digest:string;result?:{html_url?:string;integration?:string;message?:string}};
type Investigation={start_at?:string;end_at?:string;timezone?:string;query?:{mode:string;terms:string[];levels:string[]};id:string;service:string;symptom:string;status:string;created_at:string;seq:number;report?:Report;action?:Action;evidence_stale?:boolean};
type Service={id:string;name:string;team:string};
const labels:Record<string,string>={queued:'排队中',running:'调查中',completed:'调查完成',partial:'部分完成',cancelled:'已取消',failed:'失败',waiting_information:'等待补充',draft:'待审批',approved:'已批准',executing:'执行中',succeeded:'已成功',unknown:'结果待核对',invalidated:'审批已失效',rejected:'已拒绝'};
function App(){
 const[token,setToken]=useState(sessionStorage.getItem('incident-token')||''); const[user,setUser]=useState('alice');const[password,setPassword]=useState('demo-password');
 const[me,setMe]=useState<{subject:string;memberships:{team:string;role:string}[];admin:boolean}>();const[services,setServices]=useState<Service[]>([]);const[list,setList]=useState<Investigation[]>([]);const[selected,setSelected]=useState<Investigation>();const[events,setEvents]=useState<{seq:number;kind:string;payload:unknown}[]>([]);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[service,setService]=useState('');const[symptom,setSymptom]=useState('调查订单服务的超时，核对发布与代码变更，整理证据和下一步建议。');const[hours,setHours]=useState('24');const[customStart,setCustomStart]=useState('');const[customEnd,setCustomEnd]=useState('');const[clarification,setClarification]=useState('');const[title,setTitle]=useState('');const[body,setBody]=useState('');const[info,setInfo]=useState('');const[tab,setTab]=useState('report');const[adminData,setAdminData]=useState<unknown>();const cursor=useRef(0);const [memberSubject,setMemberSubject]=useState('bob');const [memberTeam,setMemberTeam]=useState('orders');const [memberRole,setMemberRole]=useState('investigator');const [targetRepo,setTargetRepo]=useState('local/incident-demo');
 async function api(path:string,method='GET',data?:unknown,extra?:Record<string,string>){const r=await fetch('/api/v1'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...extra},body:data===undefined?undefined:JSON.stringify(data)});const b=await r.json();if(r.status===401){sessionStorage.removeItem('incident-token');setToken('');setSelected(undefined);throw Error('登录已过期，请重新登录。')}if(!r.ok)throw Error(b.error||r.statusText);return b;}
 async function run(fn:()=>Promise<void>){setError('');setBusy(true);try{await fn()}catch(e){setError(String(e))}finally{setBusy(false)}}
 async function refresh(){const [m,s,l]=await Promise.all([api('/me'),api('/services'),api('/investigations')]);setMe(m);setServices(s);setList(l);if(!service&&s.length)setService(s[0].id);}
 async function load(id:string){const i=await api('/investigations/'+id);setSelected(i);return i;}
 useEffect(()=>{if(token)run(refresh)},[token]);
 useEffect(()=>{if(!selected?.id)return;let stopped=false;let controller=new AbortController();cursor.current=0;setEvents([]);const id=selected.id;
 async function connect(){while(!stopped){try{const r=await fetch(`/api/v1/investigations/${id}/events`,{headers:{Authorization:'Bearer '+token,Accept:'text/event-stream','Last-Event-ID':String(cursor.current)},signal:controller.signal});if(!r.ok)throw Error('事件流访问被拒绝');const reader=r.body!.getReader();const decoder=new TextDecoder();let buffer='';while(!stopped){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){if(chunk.includes('event: revoked')){setEvents([]);setList([]);setServices([]);setMe(undefined);setTitle('');setBody('');setSelected(undefined);throw Error('访问权限已撤销')};const data=chunk.split('\n').find(x=>x.startsWith('data: '));if(data){const ev=JSON.parse(data.slice(6));if(ev.kind==='source_invalidated'){cursor.current=ev.seq;setEvents([ev]);setTitle('');setBody('');void load(id);}else if(ev.kind==='snapshot'){cursor.current=ev.seq;setEvents([]);void load(id);}else if(ev.seq>cursor.current){cursor.current=ev.seq;setEvents(prev=>[...prev,ev]);void load(id);}}}}}catch(e){if(!stopped)setError(String(e))};if(!stopped)await new Promise(r=>setTimeout(r,1500));}}
 void connect();return()=>{stopped=true;controller.abort()};},[selected?.id,token]);
 async function open(i:Investigation){const full=await load(i.id);setTitle(full.action?.title||'修复：'+i.symptom.slice(0,60));setBody(full.action?.body||'调查摘要\n'+(full.report?.candidates?.map((c:Claim)=>c.text).join('\n')||'待进一步确认')+'\n\n证据\n'+(full.report?.evidence?.map((e:Evidence)=>e.locator).join('\n')||''));}
 const refs=(ids:string[])=>ids.map((id,j)=><a key={id} className="ref" href={'#e-'+encodeURIComponent(id)} onClick={()=>setTab('evidence')}>证据 {j+1} ↗</a>);
 if(!token)return <div className="login"><div className="brand">◈ IncidentDesk</div><h1>一句话，找到数据和证据。</h1><p>业务问数与研发调查工作台</p><form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await fetch('/identity/token',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:user,password})});if(!r.ok)throw Error('账号或密码不正确');const b=await r.json();sessionStorage.setItem('incident-token',b.access_token);setToken(b.access_token)})}}><label>演示账号<select value={user} onChange={e=>setUser(e.target.value)}><option value="alice">Alice · 订单团队审批者</option><option value="bob">Bob · 订单团队调查者</option><option value="carol">Carol · 支付团队审批者</option><option value="admin">Admin · 配置管理员</option></select></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>进入工作台 →</button></form><small>本地开发身份源 · 默认密码 demo-password<br/>自然语言找日志、发布与证据 / GitHub 接口桩</small>{error&&<p role="alert" className="error">{error}</p>}</div>;
 return <div className="layout"><aside><div className="brand">◈ IncidentDesk</div><div className="workspace">ENGINEERING WORKSPACE</div><button className="nav" onClick={()=>{setSelected(undefined);setTab('report');run(refresh)}}>▤ 统一查询工作台</button><button className="nav" onClick={()=>run(async()=>{setAdminData(await api('/memories'));setTab('memory')})}>◇ 已审核记忆</button>{me?.admin&&<button className="nav" onClick={()=>run(async()=>{setAdminData(await api('/admin'));setTab('admin')})}>⚙ 管理配置</button>}<div className="aside-bottom"><span className="dot"/> 本地开发环境<br/><small>身份：{me?.subject}<br/>GitHub：接口桩（默认）</small><button className="ghost" onClick={()=>{sessionStorage.removeItem('incident-token');setToken('');setSelected(undefined)}}>退出登录</button></div></aside><main><header><div><div className="eyebrow">INVESTIGATE · VERIFY · APPROVE</div><h1>{selected?'调查工作台':'业务数据与证据，一处查询'}</h1></div><span className="badge">{me?.memberships.map(x=>x.team).join(' / ')||'配置管理'}</span></header>{error&&<div role="alert" className="error">{error}<button className="ghost" onClick={()=>setError('')}>关闭</button></div>}
 {(tab==='admin'||tab==='memory')?<section><button className="ghost" onClick={()=>setTab('report')}>← 返回调查</button><h2>{tab==='memory'?'已审核且有效的企业记忆':'连接与访问范围'}</h2><pre>{JSON.stringify(adminData,null,2)}</pre>{tab==='admin'&&<><h3>团队访问范围</h3><label>成员<input value={memberSubject} onChange={e=>setMemberSubject(e.target.value)}/></label><div className="form-row"><select aria-label="团队" value={memberTeam} onChange={e=>setMemberTeam(e.target.value)}><option value="orders">订单团队</option><option value="payments">支付团队</option></select><select aria-label="角色" value={memberRole} onChange={e=>setMemberRole(e.target.value)}><option value="investigator">调查者</option><option value="approver">审批者</option><option value="">撤销访问</option></select><button disabled={busy} onClick={()=>run(async()=>{await api('/admin/members','PUT',{subject:memberSubject,team:memberTeam,role:memberRole});setAdminData(await api('/admin'))})}>保存权限</button></div><h3>订单服务测试仓库</h3><label>owner/repo<input value={targetRepo} onChange={e=>setTargetRepo(e.target.value)}/></label><button disabled={busy} onClick={()=>run(async()=>{await api('/admin/services/svc-17','PUT',{repo:targetRepo,enabled:true});setAdminData(await api('/admin'))})}>更新仓库并使旧审批失效</button></>}</section>:!selected?<QueryWorkbench onSessionExpired={()=>{sessionStorage.removeItem('incident-token');setToken('');setSelected(undefined)}} key={token} token={token} incidents={list} onRefresh={refresh} onOpenIncident={async(id)=>{await run(async()=>{await open(await load(id));setTab("report")})}}/>:<><button className="ghost" onClick={()=>{setSelected(undefined);setTab('report');run(refresh)}}>← 所有调查</button><section className="scope"><div><span className={'status '+selected.status}>{labels[selected.status]}</span><h2>{selected.symptom}</h2><small>{selected.service} · {selected.id}<br/>{selected.start_at&&new Date(selected.start_at).toLocaleString()} — {selected.end_at&&new Date(selected.end_at).toLocaleString()}（{selected.timezone}）{selected.query?.terms?.length?` · 关键词：${selected.query.terms.join(" / ")}`:""}</small></div><button className="danger" disabled={busy||selected.status==='cancelled'} onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/cancel`,'POST',{});await load(selected.id)})}>取消调查</button></section>{selected.evidence_stale&&<p className="error">来源已更新，现有证据过期。请重新调查后审批。</p>}<nav className="tabs">{[['report','调查结论'],['evidence','证据'],['action','工单与审批'],['trace','运行记录']].map(([k,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{t}{k==='evidence'&&` (${selected.report?.evidence?.length||0})`}</button>)}</nav>
 {tab==='report'&&<div className="columns"><section><div className="eyebrow">FINDINGS</div><h2>事实与候选原因</h2>{!selected.report?<p className="muted">正在收集资料，进度将在运行记录中显示。</p>:<><p>影响范围：<strong>{selected.report.impact}</strong> <span className="badge">{selected.report.mode}</span></p>{selected.report.candidates.map((c,i)=><article className="candidate" key={i}><span className="status partial">{c.label}</span><p>{c.text}</p>{refs(c.evidence)}</article>)}<h3>检索回答</h3>{selected.report.answer_validation&&<p className="missing">{selected.report.answer_validation}</p>}<p>{selected.report.answer}</p>{refs(selected.report.answer_evidence||[])}{selected.report.retrieval&&<p className="muted">服务/时间/关键词筛选后 {selected.report.retrieval.total_in_query??0} 条 · 条件匹配 {selected.report.retrieval.matched??0} 条 · 展示证据 {selected.report.retrieval.evidence_count??0} 条{selected.report.retrieval.sampled?" · 证据按预算抽样，仍有更多记录":""}</p>}<h3>已确认的观测</h3>{selected.report.facts.map((f,i)=><article className="fact" key={i}><p>{f.text}</p>{refs(f.evidence)}</article>)}</>}</section><div><section><h3>冲突与资料缺口</h3>{selected.report?.conflicts.map((c,i)=><p key={i}>{c.text}{refs(c.evidence)}</p>)}{selected.report?.missing.map((m,i)=><p className="missing" key={i}>{m}</p>)}{selected.report&&!selected.report.missing.length&&!selected.report.conflicts.length&&<p className="muted">本次读取未报告来源缺口；候选原因仍需验证。</p>}<h3>下一步</h3>{selected.report?.next_steps.map((s,i)=><p key={i}>{i+1}. {s}</p>)}</section><section><h3>补充信息 / 重新调查</h3><textarea value={info} onChange={e=>setInfo(e.target.value)} aria-label="补充信息"/><button disabled={busy} onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/resume`,'POST',{information:info});await load(selected.id)})}>提交并继续</button></section><section><h3>调查反馈</h3><button className="ghost" onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/feedback`,'POST',{helpful:true,confirmed:false,final_cause:''})})}>结论有帮助</button><button className="ghost" onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/badcase`,'POST',{category:'inference',label:''})})}>标记为待审核失败样本</button></section></div></div>}
 {tab==='evidence'&&<div className="evidence-grid">{selected.report?.evidence.map(e=><section key={e.id} id={'e-'+encodeURIComponent(e.id)}><span className="badge">{e.source}</span><h3>{e.locator}</h3><pre>{JSON.stringify(e.snippet,null,2)}</pre><small>事件：{e.event_time}<br/>采集：{e.collected_at}<br/>版本：{e.version}<br/>SHA-256：{e.sha256}</small></section>)}</div>}
 {tab==='action'&&<section className="action"><div className="eyebrow">CONTROLLED ACTION</div><h2>创建 GitHub Issue</h2><p>批准后将向 <strong>{selected.action?.target||'服务配置的测试仓库'}</strong> 创建一张 Issue。</p>{selected.action&&<p><span className={'status '+selected.action.state}>{labels[selected.action.state]}</span> 版本 {selected.action.version} · <small>{selected.action.digest.slice(0,16)}</small></p>}<label>标题<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>正文<textarea rows={10} value={body} onChange={e=>setBody(e.target.value)}/></label><div className="form-row"><button disabled={busy} onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/action`,'PUT',{version:selected.action?.version||0,title,body});await load(selected.id)})}>保存草稿</button>{selected.action&&<><button disabled={busy} onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/action/approve`,'POST',{version:selected.action!.version});await load(selected.id)})}>批准此版本</button><button className="ghost" disabled={busy} onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/action/reject`,'POST',{version:selected.action!.version});await load(selected.id)})}>拒绝</button></>}</div>{selected.action?.state==='unknown'&&<button disabled={busy} onClick={()=>run(async()=>{await api(`/investigations/${selected.id}/action/reconcile`,'POST',{version:selected.action!.version});await load(selected.id)})}>核对原工单（不会重新建单）</button>}<p className="muted">修改草稿将使原审批失效；只有团队审批者可以批准。</p>{selected.action?.result&&<div className="result"><p>{selected.action.result.integration||selected.action.result.message}</p>{selected.action.result.html_url&&<a href={selected.action.result.html_url} target="_blank" rel="noreferrer">查看已回读的 Issue ↗</a>}</div>}</section>}
 {tab==='trace'&&<section><h2>运行与审计记录</h2><p className="muted">游标 {cursor.current} · 自动续传与去重</p>{events.map(e=><article className="trace" key={e.seq}><span>{String(e.seq).padStart(3,'0')}</span><strong>{e.kind}</strong><pre>{JSON.stringify(e.payload,null,2)}</pre></article>)}<button className="ghost" onClick={()=>run(async()=>{const data=await api(`/investigations/${selected.id}/replay`);const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=selected.id+'-replay.json';a.click();URL.revokeObjectURL(url)})}>导出脱敏回放记录</button></section>}
 </>}<footer>IncidentDesk · 每个重要判断有证据，每个写入动作有授权。</footer></main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
